name: Update AWS Lambda

on:
  pull_request:
    types:
      - close
    paths:
      - "t212_to_digrin/**"

permissions:
  contents: read    # This is required to checkout the repository
  id-token: write   # This is required for OIDC authentication

jobs:
  update-lambda:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Build
      run: make build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_UPDATE_LAMBDA }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Update Lambda Function
      run: make update-lambda
